version: 2.1

orbs: 
  coveralls: coveralls/coveralls@1.0.6

jobs:
  run_tests:
    docker:
      - image: cimg/node:14.19.0-browsers

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            make install
      - run:
          name: Run test
          command: |
            make coverage
      - coveralls/upload


workflows:
  deploy_and_notify:
    jobs:
      - run_tests
